### ISSUE TITLE
Compile error when using latest version 5.3.13

### ISSUE THREAD

**Issue by huineng** [webpack-contrib/terser-webpack-plugin#621]
Hi, when updating from 5.3.12  to 5.3.13 and compiling it using webpack 5.98.0

i now have these errors and cannot use the latest version

```cmd
node_modules/terser-webpack-plugin/types/utils.d.ts:66:46 - error TS2307: Cannot find module 'uglify-js' or its corresponding type declarations.

66   minimizerOptions: PredefinedOptions<import("uglify-js").MinifyOptions> &
                                                ~~~~~~~~~~~

node_modules/terser-webpack-plugin/types/utils.d.ts:89:46 - error TS2307: Cannot find module '@swc/core' or its corresponding type declarations.

89   minimizerOptions: PredefinedOptions<import("@swc/core").JsMinifyOptions> &
                                                ~~~~~~~~~~~

node_modules/terser-webpack-plugin/types/utils.d.ts:111:46 - error TS2307: Cannot find module 'esbuild' or its corresponding type declarations.

111   minimizerOptions: PredefinedOptions<import("esbuild").TransformOptions> &
```

Could you have a look at this ?
Thanks
